//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CTPNHAP
    {
        public int id { get; set; }
        public int maphieu { get; set; }
        public int mathuoc { get; set; }
        [Display(Name = "Số kiểm soát")]
        public int soks { get; set; }
        [Display(Name = "Nơi sản xuất")]
        public string noisx { get; set; }
        [Display(Name = "Hạn sử dụng ")]
        [DataType(DataType.Date)]
        public System.DateTime hsd { get; set; }
        [Display(Name = "Số lượng nhập")]
        public int slnhap { get; set; }
    
        public virtual PNHAP PNHAP { get; set; }
        public virtual TONGHOP TONGHOP { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
