//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CTPXUAT
    {
        public int id { get; set; }
        public int maphieu { get; set; }
        public int mathuoc { get; set; }
        [Display(Name = "Số lượng xuất")]
        public int slxuat { get; set; }
    
        public virtual PXUAT PXUAT { get; set; }
        public virtual TONGHOP TONGHOP { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
