//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.KIEMKEs = new HashSet<KIEMKE>();
            this.PNHAPs = new HashSet<PNHAP>();
            this.PXUATs = new HashSet<PXUAT>();
        }

        [Display(Name = "Mã nhân viên")]
        public string manv { get; set; }
        [Display(Name = "Tên nhân viên")]
        public string tennv { get; set; }
        [Display(Name = "Chức vụ")]
        public string chucvu { get; set; }
        [Display(Name = "Ngày sinh")]
        [DataType(DataType.Date)]
        public System.DateTime ngaysinh { get; set; }
        [Display(Name = "Địa chỉ")]
        public string diachi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KIEMKE> KIEMKEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PNHAP> PNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PXUAT> PXUATs { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
