//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PNHAP()
        {
            this.CTPNHAPs = new HashSet<CTPNHAP>();
        }

        [Display(Name = "Mã phiếu")]
        public int maphieu { get; set; }
        [Display(Name = "Ngày nhập")]
        [DataType(DataType.Date)]
        public System.DateTime ngaynhap { get; set; }
        public string manv { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPNHAP> CTPNHAPs { get; set; }
    }
}
