//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PXUAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PXUAT()
        {
            this.CTPXUATs = new HashSet<CTPXUAT>();
        }

        [Display(Name = "Mã phiếu")]
        public int maphieu { get; set; }
        [Display(Name = "Ngày xuất")]
        [DataType(DataType.Date)]
        public System.DateTime ngayxuat { get; set; }
        public string manv { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPXUAT> CTPXUATs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
