//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class THUOC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUOC()
        {
            this.CTPNHAPs = new HashSet<CTPNHAP>();
            this.CTPXUATs = new HashSet<CTPXUAT>();
            this.TONKHOes = new HashSet<TONKHO>();
        }

        [Display(Name = "Mã thuốc")]
        public int mathuoc { get; set; }
        [Display(Name = "Tên thuốc")]
        public string tenthuoc { get; set; }
        [Display(Name = "Hoạt chất")]
        public string hoatchat { get; set; }
        [Display(Name = "Loại thuốc")]
        public string loaithuoc { get; set; }
        [Display(Name = "Đơn vị tính")]
        public string dvtinh { get; set; }
        [Display(Name = "Đơn giá")]
        public int dongia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPNHAP> CTPNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPXUAT> CTPXUATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONKHO> TONKHOes { get; set; }
        public virtual TONGHOP TONGHOP { get; set; }
    }
}
