//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TONGHOP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TONGHOP()
        {
            this.CTPNHAPs = new HashSet<CTPNHAP>();
            this.CTPXUATs = new HashSet<CTPXUAT>();
            this.TONKHOes = new HashSet<TONKHO>();
        }
    
        public int mathuoc { get; set; }
        [Display(Name = "Số lượng tồn kì trước")]
        public int sldau { get; set; }
        [Display(Name = "Số lượng nhập")]
        public int slnhap { get; set; }
        [Display(Name = "Số lượng xuất")]
        public int slxuat { get; set; }
        [Display(Name = "Số lượng hao hụt")]
        public int slhaohut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPNHAP> CTPNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPXUAT> CTPXUATs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONKHO> TONKHOes { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
