//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLThuoc.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TONKHO
    {
        public int id { get; set; }
        public int mabb { get; set; }
        public int mathuoc { get; set; }
        [Display(Name = "Số kiểm soát")]
        public int soks { get; set; }
        [Display(Name = "Hạn sử dụng")]
        [DataType(DataType.Date)]
        public System.DateTime hsd { get; set; }
        [Display(Name = "Số lượng tồn")]
        public int slton { get; set; }
        [Display(Name = "Số lượng vỡ, hỏng")]
        public int slhong { get; set; }
    
        public virtual KIEMKE KIEMKE { get; set; }
        public virtual TONGHOP TONGHOP { get; set; }
        public virtual THUOC THUOC { get; set; }
    }
}
